version:  "3.7"

services:
  app:
    build:
      context:  .
      dockerfile:   Dockerfile
    container_name: learning-app
    restart:        always
    working_dir:    /var/www
    volumes:
      - ../src:/var/www
  nginx:
    image:          nginx:1.19-alpine
    container_name: learning-nginx
    restart:        always
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

# to save resources, php composer should be run in a separate container